"use client";

import React from "react";
import AppLayout from "@/components/layout/AppLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import FinanceChart from "@/components/dashboard/FinanceChart";
import { Button } from "@/components/ui/button";
import { exportToCsv } from "@/utils/export";
import { financeData } from "../data/finance.ts";
import { showSuccess } from "@/utils/toast";
import TimeframeSelector from "../components/reports/TimeframeSelector";
import NetProfitChart from "../components/reports/NetProfitChart";
import KpiRow from "../components/reports/KpiRow";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

const Reports: React.FC = () => {
  const [months, setMonths] = React.useState<3 | 6 | 12>(6);
  const [showIncome, setShowIncome] = React.useState(true);
  const [showExpenses, setShowExpenses] = React.useState(true);
  const chartData = React.useMemo(
    () => financeData.slice(-months),
    [months],
  );
  const currentViewRows = React.useMemo(
    () => chartData.map((d) => ({ ...d, net: d.income - d.expenses })),
    [chartData],
  );

  type FinanceRow = { month: string; income: number; expenses: number; net?: number };

  const makePrintableHtmlReport = (rows: FinanceRow[], monthsSel: number) => {
    const totalIncome = rows.reduce((s, r) => s + r.income, 0);
    const totalExpenses = rows.reduce((s, r) => s + r.expenses, 0);
    const totalNet = totalIncome - totalExpenses;
    const avgIncome = totalIncome / (rows.length || 1);
    const avgExpenses = totalExpenses / (rows.length || 1);
    const currency = (n: number) => `$${n.toFixed(2)}`;

    const rowsHtml = rows
      .map(
        (r) => `
          <tr>
            <td style="padding:8px;border-bottom:1px solid #eee;">${r.month}</td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;">${currency(r.income)}</td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;">${currency(r.expenses)}</td>
            <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;">${currency((r.net ?? (r.income - r.expenses)))}</td>
          </tr>`
      )
      .join("");

    return `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Reports Summary</title>
    <style>
      body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; color:#0f172a; }
      .container { max-width: 900px; margin: 0 auto; padding: 24px; }
      .header { display:flex; justify-content:space-between; align-items:center; margin-bottom:24px; }
      .brand { font-size:20px; font-weight:600; }
      .muted { color:#64748b; font-size:12px; }
      .kpis { display:grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap:12px; margin-bottom: 12px; }
      .kpi { border:1px solid #e2e8f0; border-radius:8px; padding:12px; }
      .kpi h4 { margin:0 0 4px 0; font-size:12px; color:#475569; }
      .kpi p { margin:0; font-size:16px; font-weight:600; }
      table { width:100%; border-collapse:collapse; margin-top:16px; }
      th { text-align:left; padding:8px; background:#f8fafc; border-bottom:1px solid #e2e8f0; font-size:12px; color:#475569; }
      td { font-size:13px; }
      tfoot td { padding:8px; }
      .right { text-align:right; }
      @media print { @page { size: A4; margin: 16mm; } }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="brand">Reports Summary (${monthsSel} months)</div>
        <div class="muted">${new Date().toLocaleDateString()}</div>
      </div>
      <div class="kpis">
        <div class="kpi">
          <h4>Total Income</h4>
          <p>${currency(totalIncome)}</p>
        </div>
        <div class="kpi">
          <h4>Total Expenses</h4>
          <p>${currency(totalExpenses)}</p>
        </div>
        <div class="kpi">
          <h4>Net Profit</h4>
          <p>${currency(totalNet)}</p>
        </div>
        <div class="kpi">
          <h4>Avg Monthly Income</h4>
          <p>${currency(avgIncome)}</p>
        </div>
      </div>
      <table>
        <thead>
          <tr>
            <th>Month</th>
            <th class="right">Income</th>
            <th class="right">Expenses</th>
            <th class="right">Net</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>
      <p class="muted" style="margin-top:20px;">Generated by BizReports.</p>
    </div>
  </body>
</html>`;
  };

  const exportPdfReport = () => {
    showSuccess("Preparing report PDF...");
    const html = makePrintableHtmlReport(currentViewRows as FinanceRow[], months);
    const w = window.open("", "print", "width=900,height=1000");
    if (!w) return;
    w.document.open();
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => {
      w.print();
      w.close();
    }, 200);
  };

  return (
    <AppLayout>
      <div className="flex flex-col gap-4">
        <div className="flex items-start justify-between gap-3 flex-wrap">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Reports & Analytics</h1>
            <p className="text-sm text-muted-foreground">Finance, CRM, project performance, and productivity.</p>
          </div>
          <TimeframeSelector value={months} onChange={setMonths} />
        </div>

        {/* KPIs for the current view */}
        <KpiRow data={chartData} />

        {/* Series toggles */}
        <div className="flex items-center gap-6">
          <div className="flex items-center space-x-2">
            <Switch id="toggle-income" checked={showIncome} onCheckedChange={setShowIncome} />
            <Label htmlFor="toggle-income">Income</Label>
          </div>
          <div className="flex items-center space-x-2">
            <Switch id="toggle-expenses" checked={showExpenses} onCheckedChange={setShowExpenses} />
            <Label htmlFor="toggle-expenses">Expenses</Label>
          </div>
        </div>

        <div className="grid gap-4 lg:grid-cols-3">
          <div className="lg:col-span-2 space-y-4">
            <FinanceChart data={chartData} showIncome={showIncome} showExpenses={showExpenses} />
            <NetProfitChart data={chartData} />
          </div>
          <Card>
            <CardHeader>
              <CardTitle>Download Reports</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <Button
                onClick={() => exportToCsv(`finance-${months}m.csv`, currentViewRows)}
                className="w-full"
              >
                Export Current View CSV
              </Button>
              <Button
                onClick={() => exportToCsv("finance-full.csv", financeData.map((d) => ({ ...d, net: d.income - d.expenses })))}
                className="w-full"
              >
                Export Full (12M) CSV
              </Button>
              <Button variant="outline" onClick={exportPdfReport} className="w-full">
                Export Summary PDF
              </Button>
              <div className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">
                Export CSV/PDF will be available here.
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </AppLayout>
  );
};

export default Reports;