// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jsdwkshrrsnjhvkmdkme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzZHdrc2hycnNuamh2a21ka21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwODc2MjgsImV4cCI6MjA3OTY2MzYyOH0.2xAR868TCe1rr59mn_X7jYCJbGWeZ8t8xDdMyVz7wnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);